### ISSUE TITLE
Hypervisor Virtualbox

### ISSUE THREAD

**Issue by daniel-k** [RWTH-OS/eduOS#6]
Trying to debug latest apic problems I tried booting eduos stage10 via Virtualbox. I therefore created an iso image with grub stage2_eltorito to boot eduos and load the initrd like described in [1] and [2].

The result is the following Page Fault:
![virtualbox](https://cloud.githubusercontent.com/assets/224128/6806341/676eb8de-d248-11e4-9c89-6ae25c0f4c07.png)

[1] http://wiki.osdev.org/Bootable_El-Torito_CD_with_GRUB_Legacy
[2] http://wiki.osdev.org/Initrd

**Comment by daniel-k** [comment]
The page fault was caused by a bad GRUB version. Maybe too old for proper multiboot support. Fixed by pull request #5.

Now there's the known problem with APIC code as with other hypervisors.

**Comment by stv0g** [comment]
:+1: nice

I'm usually using QEmus monitoring shell to debug such problems:
http://en.wikibooks.org/wiki/QEMU/Monitor#info

It allows debugging the physical (non-paged) memory as well as inspecting page tables and the TLB:

"""
info mem
info tlb
x _ptr_
xp _phys_ptr_
info registers
memsave
"""

just to name a few commands...

**Comment by daniel-k** [comment]
In this particular case Qemu is not having the problems I was going to debug so it had do be another hypervisor. Parallels also shows this behaviour.

Further investigation shows that Virtualbox doesn't support the Intel MultiProcessor specification, but I'm not entirely sure if it's VirtualBox itself or maybe GRUB destroys these tables in memory.

But thanks anyway for the Qemu hint, I'm sure it will come in handy! :smiley:
